vich_uploader:
    db_driver: orm
    mappings:
        candidate_passport:
            uri_prefix: /uploads/passports
            upload_destination: '%kernel.project_dir%/public/uploads/passports'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        candidate_cv:
            uri_prefix: /uploads/cvs
            upload_destination: '%kernel.project_dir%/public/uploads/cvs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        candidate_profile:
            uri_prefix: /uploads/profiles
            upload_destination: '%kernel.project_dir%/public/uploads/profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer